-- DropForeignKey
ALTER TABLE `User` DROP FOREIGN KEY `User_tenantId_fkey`;

-- AlterTable
ALTER TABLE `User` MODIFY COLUMN `tenantId` VARCHAR(191) NULL;
ALTER TABLE `User` ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
ALTER TABLE `Tenant` ADD COLUMN `status` ENUM('ACTIVE', 'SUSPENDED', 'TRIAL') NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE `Tenant` ADD COLUMN `plan` ENUM('BASIC', 'STANDARD', 'PREMIUM') NOT NULL DEFAULT 'BASIC';

-- AddForeignKey
ALTER TABLE `User` ADD CONSTRAINT `User_tenantId_fkey` FOREIGN KEY (`tenantId`) REFERENCES `Tenant`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
