-- AlterTable
ALTER TABLE `Member` MODIFY COLUMN `plan` ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', 'DAILY_PASS') NOT NULL;

-- AlterTable
ALTER TABLE `Application` MODIFY COLUMN `plan` ENUM('MONTHLY', 'QUARTERLY', 'YEARLY', 'DAILY_PASS') NOT NULL;

-- AlterTable
ALTER TABLE `Tenant` ADD COLUMN `yearlyFee` INTEGER NULL;
